<?php

return [

    'any' => 'Any Language',

    'en' => 'English',
    'ko' => 'Korean',
    'zh' => 'Chinese',
    'ja' => 'Japanese',

    'id' => 'Indonesian',
    'ms' => 'Malay',
    'vi' => 'Vietnamese',
    'th' => 'Thai',
    'km' => 'Khmer / Cambodian',
    'lo' => 'Lao',
    'my' => 'Burmese / Myanmar',
    'tl' => 'Filipino / Tagalog',

    'uz' => 'Uzbek',
    'kk' => 'Kazakh',
    'ky' => 'Kyrgyz',
    'tk' => 'Turkmen',
    'tg' => 'Tajik',

    'ru' => 'Russian',
    'uk' => 'Ukrainian',
    'be' => 'Belarusian',
    'pl' => 'Polish',
    'cs' => 'Czech',
    'sk' => 'Slovak',
    'sl' => 'Slovenian',
    'hr' => 'Croatian',
    'sr' => 'Serbian',
    'bs' => 'Bosnian',
    'bg' => 'Bulgarian',
    'mk' => 'Macedonian',
    'ro' => 'Romanian',
    'hu' => 'Hungarian',
    'sq' => 'Albanian',
    'et' => 'Estonian',
    'lv' => 'Latvian',
    'lt' => 'Lithuanian',

    'de' => 'German',
    'fr' => 'French',
    'es' => 'Spanish',
    'pt' => 'Portuguese',
    'it' => 'Italian',
    'nl' => 'Dutch',
    'da' => 'Danish',
    'sv' => 'Swedish',
    'no' => 'Norwegian',
    'fi' => 'Finnish',
    'is' => 'Icelandic',
    'ga' => 'Irish',
    'cy' => 'Welsh',
    'eu' => 'Basque',
    'ca' => 'Catalan',
    'gl' => 'Galician',
    'mt' => 'Maltese',
    'el' => 'Greek',

    'ar' => 'Arabic',
    'fa' => 'Persian / Farsi',
    'he' => 'Hebrew',
    'tr' => 'Turkish',
    'az' => 'Azerbaijani',
    'hy' => 'Armenian',
    'ka' => 'Georgian',
    'ku' => 'Kurdish',

    'ur' => 'Urdu',
    'hi' => 'Hindi',
    'bn' => 'Bengali',
    'pa' => 'Punjabi',
    'gu' => 'Gujarati',
    'mr' => 'Marathi',
    'ne' => 'Nepali',
    'si' => 'Sinhala',
    'ta' => 'Tamil',
    'te' => 'Telugu',
    'kn' => 'Kannada',
    'ml' => 'Malayalam',
    'or' => 'Odia',

    'sw' => 'Swahili',
    'af' => 'Afrikaans',
    'am' => 'Amharic',
    'so' => 'Somali',
    'ha' => 'Hausa',
    'yo' => 'Yoruba',
    'ig' => 'Igbo',
    'zu' => 'Zulu',
    'xh' => 'Xhosa',
    'st' => 'Sesotho',
    'sn' => 'Shona',
    'rw' => 'Kinyarwanda',
    'mg' => 'Malagasy',

    'mn' => 'Mongolian',
    'bo' => 'Tibetan',
    'ug' => 'Uyghur',

    'jv' => 'Javanese',
    'su' => 'Sundanese',

    'ps' => 'Pashto',
    'sd' => 'Sindhi',

    'la' => 'Latin',
    'eo' => 'Esperanto',

    'ht' => 'Haitian Creole',

    'mi' => 'Maori',
    'sm' => 'Samoan',

    'ceb' => 'Cebuano',

    'gd' => 'Scottish Gaelic',

];